import path from "node:path";
import { listDir, dirExists, writeText, byteLength } from "../util/fs-utils.js";
import type { StackDetectionResult } from "../scan/stack-detector.js";

/** Root context budget, per Section 3 of the product spec (~12KB, progressive loading, not a whole-repo dump). */
export const ROOT_CONTEXT_BUDGET_BYTES = 12 * 1024;

const IGNORED_DIRS = new Set([
  "node_modules",
  ".git",
  ".workspace",
  ".github",
  "dist",
  "build",
  "coverage",
  "test",
  "tests",
  "__tests__",
  "vendor",
  ".venv",
  "venv",
  "target",
  ".next",
  ".cache",
]);

const MAX_MODULES = 8;

export interface ModuleCandidate {
  /** Sanitizable module name -- always derived from a real directory basename, lowercased and slug-safe. */
  name: string;
  /** Path relative to the repo root. */
  relativePath: string;
}

/**
 * Determine per-module capability blocks. For a monorepo, one module per
 * workspace package. Otherwise, one module per top-level source directory
 * (src/* if present, else repo root subdirectories), excluding common
 * non-source directories. This is real filesystem-derived detection, never
 * an invented/hardcoded module list.
 */
export async function detectModuleCandidates(
  repoPath: string,
  stack: StackDetectionResult,
): Promise<ModuleCandidate[]> {
  if (stack.monorepo.isMonorepo && stack.monorepo.packagePaths.length > 0) {
    return stack.monorepo.packagePaths.slice(0, MAX_MODULES).map((relativePath) => ({
      name: slugify(path.basename(relativePath)),
      relativePath,
    }));
  }

  const srcDir = path.join(repoPath, "src");
  const scanRoot = (await dirExists(srcDir)) ? srcDir : repoPath;
  const scanRootRelative = (await dirExists(srcDir)) ? "src" : ".";

  const entries = await listDir(scanRoot);
  const candidates: ModuleCandidate[] = [];

  for (const entry of entries.sort()) {
    if (entry.startsWith(".") || IGNORED_DIRS.has(entry)) {
      continue;
    }
    const absolute = path.join(scanRoot, entry);
    if (await dirExists(absolute)) {
      const relativePath = scanRootRelative === "." ? entry : path.join(scanRootRelative, entry);
      candidates.push({ name: slugify(entry), relativePath });
    }
    if (candidates.length >= MAX_MODULES) {
      break;
    }
  }

  return candidates;
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "-")
    .replace(/^-+|-+$/g, "") || "module";
}

export interface GeneratedContext {
  rootContextPath: string;
  rootContextBytes: number;
  budgetBytes: number;
  modulePaths: string[];
  moduleNames: string[];
}

/**
 * Write root-context.md plus one file per detected module under
 * .workspace/context/, respecting the root-context byte budget. If the
 * generated root context would exceed budget, module summaries are trimmed
 * (listed by name only, without descriptions) until it fits.
 */
export async function generateContext(
  workspaceDir: string,
  repoPath: string,
  repoName: string,
  stack: StackDetectionResult,
  modules: ModuleCandidate[],
): Promise<GeneratedContext> {
  const contextDir = path.join(workspaceDir, "context");
  const modulesDir = path.join(contextDir, "modules");
  const rootContextPath = path.join(contextDir, "root-context.md");

  const modulePaths: string[] = [];
  for (const module of modules) {
    const modulePath = path.join(modulesDir, `${module.name}.md`);
    const content = buildModuleContent(module);
    await writeText(modulePath, content);
    modulePaths.push(modulePath);
  }

  let rootContent = buildRootContext(repoName, stack, modules, true);
  if (byteLength(rootContent) > ROOT_CONTEXT_BUDGET_BYTES) {
    rootContent = buildRootContext(repoName, stack, modules, false);
  }

  await writeText(rootContextPath, rootContent);

  return {
    rootContextPath,
    rootContextBytes: byteLength(rootContent),
    budgetBytes: ROOT_CONTEXT_BUDGET_BYTES,
    modulePaths,
    moduleNames: modules.map((module) => module.name),
  };
}

function buildRootContext(
  repoName: string,
  stack: StackDetectionResult,
  modules: ModuleCandidate[],
  withDescriptions: boolean,
): string {
  const moduleLines = modules.map((module) => {
    if (withDescriptions) {
      return `- **${module.name}** (\`${module.relativePath}\`) -- see \`.workspace/context/modules/${module.name}.md\` for details, loaded on demand.`;
    }
    return `- ${module.name}`;
  });

  return `# Root Context -- ${repoName}

Generated by AgenticWorkspace. This file is loaded at the start of every
Claude Code session in this repo. It stays small on purpose: detail lives in
per-module files under \`.workspace/context/modules/\`, loaded on demand
instead of all at once.

## Stack

- Language: ${stack.language}
- Package manager: ${stack.packageManager}
- Monorepo: ${stack.monorepo.isMonorepo ? `yes, ${stack.monorepo.packageCount} packages` : "no"}

## Modules

${moduleLines.length > 0 ? moduleLines.join("\n") : "No modules detected yet. Re-run `agenticworkspace init` after adding source directories."}

## Session handoff

Check \`.workspace/handoff/\` for the most recent session's notes before
starting new work. Run \`agenticworkspace status --json\` for a machine-readable
snapshot of workspace health.
`;
}

function buildModuleContent(module: ModuleCandidate): string {
  return `# Module: ${module.name}

Path: \`${module.relativePath}\`

This is a per-module capability block, loaded on demand rather than always
included in the root context. Extend this file with what a session working
in \`${module.relativePath}\` actually needs to know: key entry points,
conventions specific to this module, and anything that would otherwise need
rediscovering every session.
`;
}
